apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: daily-hacker-news-bot
  namespace: daily-hacker-news-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: daily-hacker-news-bot
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: hacker-news-discord-webhook
    - secretKey: SOURCE_URL
      remoteRef:
        key: hacker-news-source-url
