apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mackerel-apikey
  namespace: mackerel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mackerel-apikey
    creationPolicy: Owner
  data:
    - secretKey: apikey
      remoteRef:
        key: mackerel-apikey
