apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newrelic-license
  namespace: newrelic
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: newrelic-license
    creationPolicy: Owner
  data:
    - secretKey: licenseKey
      remoteRef:
        key: newrelic-license-key
