apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daily-hacker-news-bot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yashikota/kotarnetes.git
    targetRevision: main
    path: manifests/daily-hacker-news-bot
  destination:
    server: https://kubernetes.default.svc
    namespace: daily-hacker-news-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
