apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newrelic
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm-charts.newrelic.com
      chart: nri-bundle
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/manifests/monitoring/newrelic-values.yaml
    - repoURL: https://github.com/yashikota/kotarnetes.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: newrelic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
