apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-hacker-news-bot
spec:
  schedule: "0 12 * * *"
  timeZone: "Asia/Tokyo"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daily-hacker-news-bot
              image: ghcr.io/a-kaibu/daily-hacker-news-bot:latest
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: daily-hacker-news-bot
          restartPolicy: OnFailure
