apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-trending-ja
spec:
  schedule: "0 5 * * *"
  timeZone: "Asia/Tokyo"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: github-trending-ja
              image: ghcr.io/yashikota/github-trending-ja:latest
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: github-trending-ja
          restartPolicy: OnFailure
