apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-sdk-server-tls
        namespace: external-secrets
        key: tls.crt
      organizationID: dbb5eb37-8e70-4019-a262-b3d500c1d4dc
      projectID: 01ba1ecf-a143-41e1-ad8c-b3d500c5bff7
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            namespace: external-secrets
            key: token
